name: Create docker image
on:
  workflow_call:
    inputs:
      runner:
        description: What build agent to use
        type: string
        required: false
        default: 'ubuntu-latest'
      artifact-name:
        description: The name of the artifact
        type: string
        required: false
        default: 'artifact'
      container-registry:
        description: The container registry to use
        type: string
        required: false
        default: 'docker.io'
        secret: true
#    outputs:

jobs:
  create-docker-image:
    name: Create docker image
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

