name: Create docker image
on:
  workflow_call:
    inputs:
      runner:
        description: What build agent to use
        type: string
        required: false
        default: 'ubuntu-latest'
      artifact-name:
        description: The name of the artifact
        type: string
        required: false
        default: 'artifact'
      registry:
        description: The container registry to use
        type: string
        required: false
        default: 'docker.io'
      docker-image:
        description: The name of the docker image
        type: string
        required: true
    secrets:
      container-registry-password:
        required: true
#    outputs:

jobs:
  create-docker-image:
    name: Create docker image
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Print event name
        run: echo "The event name is ${{ github.event_name }}"
      - name: Print docker image
        run: echo "The docker image is ${{ inputs.docker-image }}"
      - name: Print owner
        run: echo "The owner is ${{ fromJSON(inputs.docker-image).owner }}"
      - name: Print image
        run: echo "The image is ${{ fromJSON(inputs.docker-image).image }}"
      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ fromJSON(inputs.docker-image).registry }}
          username: ${{ fromJSON(inputs.docker-image).owner }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
