name: Create docker image
on:
  workflow_call:
    inputs:
      runner:
        description: What build agent to use
        type: string
        required: false
        default: 'ubuntu-latest'
      artifact-name:
        description: The name of the artifact
        type: string
        required: false
        default: 'artifact'
#    outputs:

jobs:
  create-docker-image:
    name: Create docker image
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Print artifact
        run: ls
#      - name: Print event name
#          run: echo "The event name is ${{ github.event_name }}"
#      - name: Login to Container Registry
#          if: github.event_name != 'pull_request'
#          uses: docker/login-action@v3
#          with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ env.USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#      - name: Extract metadata (tags, labels) for Docker
#          id: meta
#          uses: docker/metadata-action@v5
#          with:
#          images: |
#            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.PACKAGE }}
#          tags: |
#            type=semver,pattern={{version}},value=${{ inputs.version }}
#            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
