name: Populate docker image specifications
on:
  workflow_call:
    inputs:
      ref:
        description: 'Which ref to check out'
        type: string
        required: false
      runner:
        description: 'What build agent to use'
        type: string
        required: false
        default: 'ubuntu-latest'
      registry:
        description: 'The container registry to use'
        type: string
        required: false
        default: ghcr.io
      owner:
        description: 'The owner of the docker image'
        type: string
        required: false
        default: ${{ github.actor }}
      image:
        description: 'The name of the docker image'
        type: string
        required: true
    outputs:
      docker:
        description: The docker image specifications in JSON format
        value: ${{ jobs.container-registry-specifications.outputs.json }}

jobs:
  container-registry-specifications:
    name: Set docker image name
    runs-on: ${{ inputs.runner }}
    env:
      REGISTRY: ${{ inputs.registry }}
      OWNER: ${{ inputs.owner }}
      IMAGE: ${{ inputs.image }}
    outputs:
      json: ${{ steps.json.outputs.json }}
    steps:
      - name: Set docker image properties
        id: docker-image
        run: |
          echo "registry=${{ env.REGISTRY }}" >> $GITHUB_OUTPUT
          echo "owner=${{ env.OWNER }}" >> $GITHUB_OUTPUT
          echo "image-name=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
      - name: Add JSON to output
        id: json
        run: echo "json=$(echo '${{ toJSON(steps.docker-image.outputs) }}' | jq -c '.')" >> $GITHUB_OUTPUT


