name: Populate docker image specifications
on:
  workflow_call:
    inputs:
      ref:
        description: 'Which ref to check out'
        type: string
        required: false
      runner:
        description: 'What build agent to use'
        type: string
        required: false
        default: 'ubuntu-latest'
      registry:
        description: 'The container registry to use'
        type: string
        required: false
        default: ghcr.io
      owner:
        description: 'The owner of the docker image'
        type: string
        required: false
        default: ${{ github.actor }}
      image:
        description: 'The name of the docker image'
        type: string
        required: true
    outputs:
      docker:
        description: The docker image specifications in JSON format
        value: ${{ jobs.container-registry-specifications.outputs.docker-specifications }}

jobs:
  container-registry-specifications:
    name: Provide docker image specifications
    runs-on: ${{ inputs.runner }}
    env:
      REGISTRY: ${{ inputs.registry }}
      OWNER: ${{ inputs.owner }}
      IMAGE: ${{ inputs.image }}
    outputs:
      docker-specifications: ${{ steps.populate-json-details.outputs.docker-specifications }}
    steps:
      - name: Populate docker image specifications
        id: docker-specifications
        run: |
          echo "registry=${{ env.REGISTRY }}" >> $GITHUB_OUTPUT
          echo "owner=${{ env.OWNER }}" >> $GITHUB_OUTPUT
          echo "image-name=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
      - name: Convert docker image specifications to JSON
        id: populate-json-details
        run: echo "docker-specifications=$(echo '${{ toJSON(steps.docker-specifications.outputs) }}' | jq -c '.')" >> $GITHUB_OUTPUT


